name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        run: npm test

      - name: List report files
        if: always()
        run: |
          echo "Arquivos gerados:"
          find cypress/reports -type f 2>/dev/null || true

      - name: Upload Cypress JSON Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-results
          path: cypress/reports/.jsons/
          if-no-files-found: error

  report:
    runs-on: ubuntu-latest

    needs: tests

    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download Cypress JSON Results
        uses: actions/download-artifact@v4
        with:
          name: cypress-json-results
          path: cypress/reports/.jsons/

      - name: List downloaded files
        run: |
          echo "JSONs baixados:"
          find cypress/reports -type f

      - name: Generate Mochawesome Report
        run: |
          npx mochawesome-merge "cypress/reports/.jsons/*.json" > cypress/reports/report.json

      - name: Generate HTML Report
        run: |
          npx marge cypress/reports/report.json \
            -f cypress-report \
            -o cypress/reports

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/
